apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/uukomadu/devops-code-challenge2.git
    targetRevision: gitops
    path: helm/node-app
    helm:
      releaseName: node-app
  destination:
    server: https://kubernetes.default.svc
    namespace: node-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
